const {test}=require('node:test');
const assert=require('node:assert/strict');
const E=require('./public/engine.js');
const buy=(s,extra={})=>E.act(s,'/api/order',{symbol:'NOVA',side:'buy',kind:'market',quantity:10,...extra},10000000);
test('market buy/sell preserves cash and cost',()=>{const s=E.fresh();buy(s);assert.equal(s.user.cash,99872000);assert.equal(s.positions[0].quantity,10);buy(s,{side:'sell',quantity:4});assert.equal(s.positions[0].cost,76800);buy(s,{side:'sell',quantity:6});assert.equal(s.user.cash,100000000);assert.equal(s.positions.length,0);E.validate(s);});
test('reservations prevent overspending and cancellation releases cash',()=>{const s=E.fresh();buy(s,{kind:'limit',limit_price:100,quantity:1000000});assert.throws(()=>buy(s),/資金不足/);E.act(s,'/api/cancel',{id:1});buy(s);E.validate(s);});
test('sell reservations prevent overselling',()=>{const s=E.fresh();buy(s);buy(s,{side:'sell',kind:'limit',limit_price:100000000});assert.throws(()=>buy(s,{side:'sell',quantity:1}),/股數不足/);E.act(s,'/api/cancel',{id:2});buy(s,{side:'sell'});E.validate(s);});
test('limit fills on price crossing, ticks no more than once per 3s',()=>{const s=E.fresh(10000000);buy(s,{kind:'limit',limit_price:12790});E.tick(s,10002000,()=>0);assert.equal(s.orders[0].status,'open');E.tick(s,10003000,()=>0);assert.equal(s.orders[0].status,'filled');const cash=s.user.cash;E.tick(s,10003001,()=>0);assert.equal(s.user.cash,cash);assert.ok(s.stocks[0].price<12800);E.validate(s);});
test('reopening does not replay offline ticks',()=>{const s=E.fresh(10000000);const reference=E.fresh(10000000);E.tick(reference,10003000,()=>0);E.tick(s,10000000+86400000,()=>0);assert.equal(s.stocks[0].price,reference.stocks[0].price);assert.equal(s.stocks[0].candles.length,90);E.validate(s);});
test('reject invalid order inputs',()=>{for(const quantity of [0,-1,1.5,NaN,Infinity,true,1000001]){assert.throws(()=>buy(E.fresh(),{quantity}));}assert.throws(()=>buy(E.fresh(),{side:'sell'}));});
test('save JSON roundtrip and malformed saves',()=>{const s=E.fresh();buy(s);assert.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);for(const mutate of [s=>s.version=99,s=>s.user.cash=-1,s=>s.positions[0].symbol='<script>',s=>s.stocks[0].price=NaN,s=>s.orders[0].quantity='10',s=>s.stocks[0].candles[0].close=-1]){const bad=structuredClone(s);mutate(bad);assert.throws(()=>E.validate(bad));}});
test('completed history bounded while all pending orders retained',()=>{const s=E.fresh();buy(s,{kind:'limit',limit_price:100,quantity:1});for(let i=0;i<220;i++)buy(s,{quantity:1});assert.equal(s.orders.length,201);assert.equal(s.orders[0].status,'open');E.validate(s);});
test('import rejects over-reserved assets',()=>{const s=E.fresh();buy(s,{kind:'limit',limit_price:100,quantity:100});s.user.cash=1;assert.throws(()=>E.validate(s));});
function rng(seed){return ()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
test('independent seeded histories remain continuous and end at current quote',()=>{const s=E.fresh(10000000,rng(42));E.validate(s);const curves=s.stocks.map(t=>t.candles.map(c=>c.close/t.opening).join(','));assert.equal(new Set(curves).size,6);for(const t of s.stocks){assert.equal(t.candles.at(-1).close,t.price);for(let i=1;i<90;i++)assert.equal(t.candles[i].open,t.candles[i-1].close);}});
test('old saves gain independent regimes without changing holdings or historical bars',()=>{const s=E.fresh(10000000,rng(1));buy(s);const old=JSON.parse(JSON.stringify(s));const bars=JSON.stringify(old.stocks.map(t=>t.candles.slice(0,-1)));const restored=E.validate(old);E.tick(restored,10003000,rng(12));assert.equal(restored.positions[0].quantity,10);assert.equal(JSON.stringify(restored.stocks.map(t=>t.candles.slice(0,-1))),bars);assert.ok(restored.stocks.every(t=>t.regime));E.validate(restored);});
test('company returns diverge across a long deterministic simulation',()=>{const s=E.fresh(10000000,rng(5)),random=rng(12345),returns=s.stocks.map(()=>[]);for(let i=1;i<=3000;i++){const before=s.stocks.map(t=>t.price);E.tick(s,10000000+i*3000,random);s.stocks.forEach((t,k)=>returns[k].push(t.price/before[k]-1));}const corr=(a,b)=>{const mean=x=>x.reduce((s,n)=>s+n,0)/x.length,ma=mean(a),mb=mean(b);let cov=0,va=0,vb=0;for(let i=0;i<a.length;i++){cov+=(a[i]-ma)*(b[i]-mb);va+=(a[i]-ma)**2;vb+=(b[i]-mb)**2;}return cov/Math.sqrt(va*vb);};for(let i=0;i<6;i++)for(let j=i+1;j<6;j++)assert.ok(Math.abs(corr(returns[i],returns[j]))<.2);const variance=a=>a.reduce((s,x)=>s+x*x,0)/a.length;assert.ok(variance(returns[2])>variance(returns[3])*1.5);E.validate(s);});
test('malformed imported regimes rejected',()=>{for(const bad of [{drift:Infinity,scale:1,remaining:10},{drift:0,scale:99,remaining:10},{drift:0,scale:1,remaining:-1}]){const s=E.fresh();s.stocks[0].regime=bad;assert.throws(()=>E.validate(s));}});
